title: Little corner 
url: "https://martamarchiori.github.io"
baseurl: "https://martamarchiori.github.io"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana, icons from https://www.flaticon.com/"

sass:
    style: compressed
    sass_dir: _sass

plugins:
  - jekyll-seo-tag

nav:
 - name: "About"
   link: "https://martamarchiori.github.io/"
 - name: "Projects"
   link: "projects"
 - name: "CV"
   link: "cv.pdf"
 - name: "Contact"
   link: "contact"
