title: Little corner 
url: "https://martam21.github.io/MyWebSite/"
baseurl: "/MyWebSite"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana, icons from https://www.flaticon.com/"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Marta"
   link: "/MyWebSite/"
 - name: "Resume"
   link: "https://docs.google.com/document/d/1gmWQ3bsc3Ewb46Vkpg66y8DUWb62rZFDpQwOBJObcHI/edit?usp=sharing"
 - name: "Contact"
   link: "contact"
