title: Little corner 
url: "https://martamarchiori.github.io"
baseurl: "https://martamarchiori.github.io"
tagline: "A CV based website that collect my academic inspirations and experiences"
description: "A CV based website that collect my academic inspirations and experiences"
google_site_verification: "eLQAL9-dHJOZyajbH0VuBMlx-iUPr4eNaSnYBJplkWM"
social:
  name: Marta Marchiori Manerba 
  links:
    - https://twitter.com/Marta_Marchiori
    - https://www.facebook.com/marta.b.marchiori/
    - https://www.linkedin.com/in/marta-marchiori-manerba/
    - https://github.com/MartaMarchiori
twitter:
  username: Marta_Marchiori

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana, icons from https://www.flaticon.com/"

sass:
    style: compressed
    sass_dir: _sass

plugins:
  - jekyll-seo-tag

nav:
 - name: "About"
   link: "https://martamarchiori.github.io/"
 - name: "Projects"
   link: "projects"
 - name: "CV"
   link: "cv.pdf"
 - name: "Contact"
   link: "contact"
